### ISSUE TITLE
Is there any document for a developer?

### ISSUE THREAD

**Issue by lshmouse** [zstackio/zstack#1268]
ZStack is very impressing opensource project about IAAS. 

I am trying to learn this project and try to became a  developer by building it from source and deploying the service manually using the distribution from the build.

Currently I build the project by: mvn clean install package assembly:single -DskipTests and got a zstack.war. But I don't know how to start the service?  The installation document is about deploying from a zstack ISO and I can not find the zstack-ctl  in the community version.

Is there any document for a developer? Thanks~

**Comment by live4thee** [comment]
Navigate to the "Resource Download" section from [ZStack](https://en.zstack.io/), and under TAB "Documentation" there are

1. Installation Guide
2. zstack-ctl/cli Manual
3. API reference

The missing "zstack-ctl" is really a chicken-egg problem for you.  The initial deployment is expected to be ISO based (which contains all required packages/dependencies - this is due to the fact that a production deployment might not have an internet connection).  The war file is designed to **upgrade** the management node and agents, but not for the purpose of a fresh installation.
